### ISSUE TITLE
unavailable sample data source  

### ISSUE THREAD

**Issue by jing0703** [rhinempi/sparkhit#5]
Hi, I want to follow the usecase example and download it to run on AWS, but the data is removed from https://s3.computational.bio.uni-giessen.de/swift/v1/sparkhitTool/sparkhitSummer.tar.gz

Could you help me with it? Thank you very much!

**Comment by rhinempi** [comment]
Hi, this dataset was only used in the summer school last year. Thus it has been deleted from the cloud storage. Let me try to find a local backup in our server.

Li

**Comment by jing0703** [comment]
Hi Li, thank you very much for your help! I got all the expected output files when running the sparkhit function on one EC2 instance (./sparkhit-latest/bin/sparkhit recruiter --driver-memory 1G --executor-memory 1G -fastq ./sparkhit-latest/example/Stool-SRS016203.fq.gz -reference ./sparkhit-latest/example/Ecoli.fa -outfile ~/sparkhit-latest/example/stool-result). 

However, there is no result files when I run the same function on my EC2 spark cluster (./sparkhit-latest/bin/sparkhit recruiter --master spark://ec2-107-21-13-191.compute-1.amazonaws.com:7077 --driver-memory 1G --executor-memory 1G -fastq ./sparkhit-latest/example/Stool-SRS016203.fq.gz -reference ./sparkhit-latest/example/Ecoli.fa -outfile ./sparkhit-latest/example/stool-result1). 

Could you please help me with it? Thank you very much!

![image](https://user-images.githubusercontent.com/37348521/59547283-6c3ea300-8f0a-11e9-9bdc-b60e8cf9bf51.png)
There is no error and this is the logging:
`ubuntu@ip-10-0-0-9:~$ /usr/local/spark/bin/spark-submit --master spark://ec2-107-21-13-191.compute-1.amazonaws.com:7077 --driver-memory 1G --executor-memory 1G --class uni.bielefeld.cmg.sparkhit.main.Main ./sparkhit-latest/lib/original-sparkhit-1.0.jar -fastq ./sparkhit-latest/example/Stool-SRS016203.fq.gz -reference ./sparkhit-latest/example/Ecoli.fa -outfile /home/ubuntu/sparkhit-latest/example/stool-result1
2019-06-15 05:02:02 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
SparkHit 05:02:03 SparkHit recruiter initiating ... 
SparkHit 05:02:03 interpreting parameters.
SparkHit 05:02:03 Output file : 
SparkHit 05:02:03 	/home/ubuntu/sparkhit-latest/example/stool-result1
SparkHit 05:02:03 already exists, will be overwrite.
SparkHit 05:02:03 Initiating Spark context ...
SparkHit 05:02:03 Start Spark framework
2019-06-15 05:02:03 INFO  SparkContext:54 - Running Spark version 2.3.1
2019-06-15 05:02:03 INFO  SparkContext:54 - Submitted application: SparkHit
2019-06-15 05:02:03 INFO  SecurityManager:54 - Changing view acls to: ubuntu
2019-06-15 05:02:03 INFO  SecurityManager:54 - Changing modify acls to: ubuntu
2019-06-15 05:02:03 INFO  SecurityManager:54 - Changing view acls groups to: 
2019-06-15 05:02:03 INFO  SecurityManager:54 - Changing modify acls groups to: 
2019-06-15 05:02:03 INFO  SecurityManager:54 - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(ubuntu); groups with view permissions: Set(); users  with modify permissions: Set(ubuntu); groups with modify permissions: Set()
2019-06-15 05:02:03 INFO  Utils:54 - Successfully started service 'sparkDriver' on port 35339.
2019-06-15 05:02:03 INFO  SparkEnv:54 - Registering MapOutputTracker
2019-06-15 05:02:03 INFO  SparkEnv:54 - Registering BlockManagerMaster
2019-06-15 05:02:03 INFO  BlockManagerMasterEndpoint:54 - Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
2019-06-15 05:02:03 INFO  BlockManagerMasterEndpoint:54 - BlockManagerMasterEndpoint up
2019-06-15 05:02:03 INFO  DiskBlockManager:54 - Created local directory at /tmp/blockmgr-2877a608-fd02-4516-9815-d035524aac81
2019-06-15 05:02:03 INFO  MemoryStore:54 - MemoryStore started with capacity 366.3 MB
2019-06-15 05:02:03 INFO  SparkEnv:54 - Registering OutputCommitCoordinator
2019-06-15 05:02:03 INFO  log:192 - Logging initialized @2094ms
2019-06-15 05:02:03 INFO  Server:346 - jetty-9.3.z-SNAPSHOT
2019-06-15 05:02:03 INFO  Server:414 - Started @2195ms
2019-06-15 05:02:03 INFO  AbstractConnector:278 - Started ServerConnector@22bdd442{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2019-06-15 05:02:03 INFO  Utils:54 - Successfully started service 'SparkUI' on port 4040.
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@41382722{/jobs,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@c41709a{/jobs/json,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@7db0565c{/jobs/job,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@52eacb4b{/jobs/job/json,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@5528a42c{/stages,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@2a551a63{/stages/json,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@1a6f5124{/stages/stage,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@cc62a3b{/stages/stage/json,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6cc0bcf6{/stages/pool,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@29539e36{/stages/pool/json,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@32f61a31{/storage,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@f5c79a6{/storage/json,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@669253b7{/storage/rdd,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@5305c37d{/storage/rdd/json,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@51a06cbe{/environment,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@3dddbe65{/environment/json,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@49a64d82{/executors,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@344561e0{/executors/json,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@66d23e4a{/executors/threadDump,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@36ac8a63{/executors/threadDump/json,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@4d9d1b69{/static,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@2d35442b{/,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@27f9e982{/api,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@581d969c{/jobs/job/kill,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@22db8f4{/stages/stage/kill,null,AVAILABLE,@Spark}
2019-06-15 05:02:03 INFO  SparkUI:54 - Bound SparkUI to 0.0.0.0, and started at http://ec2-107-21-13-191.compute-1.amazonaws.com:4040
2019-06-15 05:02:04 INFO  SparkContext:54 - Added JAR file:/home/ubuntu/./sparkhit-latest/lib/original-sparkhit-1.0.jar at spark://ip-10-0-0-9.ec2.internal:35339/jars/original-sparkhit-1.0.jar with timestamp 1560574924059
2019-06-15 05:02:04 INFO  StandaloneAppClient$ClientEndpoint:54 - Connecting to master spark://ec2-107-21-13-191.compute-1.amazonaws.com:7077...
2019-06-15 05:02:04 INFO  TransportClientFactory:267 - Successfully created connection to ec2-107-21-13-191.compute-1.amazonaws.com/10.0.0.9:7077 after 29 ms (0 ms spent in bootstraps)
2019-06-15 05:02:04 INFO  StandaloneSchedulerBackend:54 - Connected to Spark cluster with app ID app-20190615050204-0003
2019-06-15 05:02:04 INFO  StandaloneAppClient$ClientEndpoint:54 - Executor added: app-20190615050204-0003/0 on worker-20190615032012-10.0.0.5-35655 (10.0.0.5:35655) with 6 core(s)
2019-06-15 05:02:04 INFO  StandaloneSchedulerBackend:54 - Granted executor ID app-20190615050204-0003/0 on hostPort 10.0.0.5:35655 with 6 core(s), 1024.0 MB RAM
2019-06-15 05:02:04 INFO  StandaloneAppClient$ClientEndpoint:54 - Executor added: app-20190615050204-0003/1 on worker-20190615032005-10.0.0.7-42383 (10.0.0.7:42383) with 6 core(s)
2019-06-15 05:02:04 INFO  StandaloneSchedulerBackend:54 - Granted executor ID app-20190615050204-0003/1 on hostPort 10.0.0.7:42383 with 6 core(s), 1024.0 MB RAM
2019-06-15 05:02:04 INFO  StandaloneAppClient$ClientEndpoint:54 - Executor added: app-20190615050204-0003/2 on worker-20190615032008-10.0.0.12-33029 (10.0.0.12:33029) with 6 core(s)
2019-06-15 05:02:04 INFO  StandaloneSchedulerBackend:54 - Granted executor ID app-20190615050204-0003/2 on hostPort 10.0.0.12:33029 with 6 core(s), 1024.0 MB RAM
2019-06-15 05:02:04 INFO  Utils:54 - Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46643.
2019-06-15 05:02:04 INFO  NettyBlockTransferService:54 - Server created on ip-10-0-0-9.ec2.internal:46643
2019-06-15 05:02:04 INFO  BlockManager:54 - Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
2019-06-15 05:02:04 INFO  StandaloneAppClient$ClientEndpoint:54 - Executor updated: app-20190615050204-0003/1 is now RUNNING
2019-06-15 05:02:04 INFO  StandaloneAppClient$ClientEndpoint:54 - Executor updated: app-20190615050204-0003/0 is now RUNNING
2019-06-15 05:02:04 INFO  StandaloneAppClient$ClientEndpoint:54 - Executor updated: app-20190615050204-0003/2 is now RUNNING
2019-06-15 05:02:04 INFO  BlockManagerMaster:54 - Registering BlockManager BlockManagerId(driver, ip-10-0-0-9.ec2.internal, 46643, None)
2019-06-15 05:02:04 INFO  BlockManagerMasterEndpoint:54 - Registering block manager ip-10-0-0-9.ec2.internal:46643 with 366.3 MB RAM, BlockManagerId(driver, ip-10-0-0-9.ec2.internal, 46643, None)
2019-06-15 05:02:04 INFO  BlockManagerMaster:54 - Registered BlockManager BlockManagerId(driver, ip-10-0-0-9.ec2.internal, 46643, None)
2019-06-15 05:02:04 INFO  BlockManager:54 - Initialized BlockManager: BlockManagerId(driver, ip-10-0-0-9.ec2.internal, 46643, None)
2019-06-15 05:02:04 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@47b2e9e1{/metrics/json,null,AVAILABLE,@Spark}
2019-06-15 05:02:04 INFO  StandaloneSchedulerBackend:54 - SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
2019-06-15 05:02:05 INFO  MemoryStore:54 - Block broadcast_0 stored as values in memory (estimated size 237.8 KB, free 366.1 MB)
2019-06-15 05:02:05 INFO  MemoryStore:54 - Block broadcast_0_piece0 stored as bytes in memory (estimated size 23.2 KB, free 366.0 MB)
2019-06-15 05:02:05 INFO  BlockManagerInfo:54 - Added broadcast_0_piece0 in memory on ip-10-0-0-9.ec2.internal:46643 (size: 23.2 KB, free: 366.3 MB)
2019-06-15 05:02:05 INFO  SparkContext:54 - Created broadcast 0 from textFile at SparkPipe.java:403
SparkHit 05:02:05 start building reference index.
SparkHit 05:02:05 parsing parameters ...
SparkHit 05:02:05 kmer size : 11
SparkHit 05:02:05 start loading reference sequence.
SparkHit 05:02:05 Input fasta file is a local file : 
SparkHit 05:02:05 	/home/ubuntu/./sparkhit-latest/example/Ecoli.fa
SparkHit 05:02:05 Reading fasta file using BufferedReader
SparkHit 05:02:06 loaded 4641652 bases, 1 contigs.
SparkHit 05:02:06 took 259 ms.
SparkHit 05:02:06 start building reference index.
SparkHit 05:02:07 took 1857 ms.
2019-06-15 05:02:07 INFO  MemoryStore:54 - Block broadcast_1 stored as values in memory (estimated size 1208.9 KB, free 364.9 MB)
2019-06-15 05:02:07 INFO  CoarseGrainedSchedulerBackend$DriverEndpoint:54 - Registered executor NettyRpcEndpointRef(spark-client://Executor) (10.0.0.12:38318) with ID 2
2019-06-15 05:02:07 INFO  CoarseGrainedSchedulerBackend$DriverEndpoint:54 - Registered executor NettyRpcEndpointRef(spark-client://Executor) (10.0.0.7:43604) with ID 1
2019-06-15 05:02:07 INFO  CoarseGrainedSchedulerBackend$DriverEndpoint:54 - Registered executor NettyRpcEndpointRef(spark-client://Executor) (10.0.0.5:56290) with ID 0
2019-06-15 05:02:07 INFO  MemoryStore:54 - Block broadcast_1_piece0 stored as bytes in memory (estimated size 1472.5 KB, free 363.4 MB)
2019-06-15 05:02:07 INFO  BlockManagerInfo:54 - Added broadcast_1_piece0 in memory on ip-10-0-0-9.ec2.internal:46643 (size: 1472.5 KB, free: 364.8 MB)
2019-06-15 05:02:07 INFO  SparkContext:54 - Created broadcast 1 from broadcast at SparkPipe.java:411
2019-06-15 05:02:07 INFO  MemoryStore:54 - Block broadcast_2 stored as values in memory (estimated size 192.0 B, free 363.4 MB)
2019-06-15 05:02:07 INFO  MemoryStore:54 - Block broadcast_2_piece0 stored as bytes in memory (estimated size 80.0 B, free 363.4 MB)
2019-06-15 05:02:07 INFO  BlockManagerInfo:54 - Added broadcast_2_piece0 in memory on ip-10-0-0-9.ec2.internal:46643 (size: 80.0 B, free: 364.8 MB)
2019-06-15 05:02:07 INFO  SparkContext:54 - Created broadcast 2 from broadcast at SparkPipe.java:412
2019-06-15 05:02:07 INFO  MemoryStore:54 - Block broadcast_3 stored as values in memory (estimated size 147.2 MB, free 216.2 MB)
2019-06-15 05:02:08 INFO  BlockManagerMasterEndpoint:54 - Registering block manager 10.0.0.12:45298 with 366.3 MB RAM, BlockManagerId(2, 10.0.0.12, 45298, None)
2019-06-15 05:02:08 INFO  BlockManagerMasterEndpoint:54 - Registering block manager 10.0.0.7:33955 with 366.3 MB RAM, BlockManagerId(1, 10.0.0.7, 33955, None)
2019-06-15 05:02:08 INFO  BlockManagerMasterEndpoint:54 - Registering block manager 10.0.0.5:45573 with 366.3 MB RAM, BlockManagerId(0, 10.0.0.5, 45573, None)
2019-06-15 05:02:08 INFO  MemoryStore:54 - Block broadcast_3_piece0 stored as bytes in memory (estimated size 4.0 MB, free 212.2 MB)
2019-06-15 05:02:08 INFO  BlockManagerInfo:54 - Added broadcast_3_piece0 in memory on ip-10-0-0-9.ec2.internal:46643 (size: 4.0 MB, free: 360.8 MB)
2019-06-15 05:02:08 INFO  MemoryStore:54 - Block broadcast_3_piece1 stored as bytes in memory (estimated size 4.0 MB, free 208.2 MB)
2019-06-15 05:02:08 INFO  BlockManagerInfo:54 - Added broadcast_3_piece1 in memory on ip-10-0-0-9.ec2.internal:46643 (size: 4.0 MB, free: 356.8 MB)
2019-06-15 05:02:08 INFO  MemoryStore:54 - Block broadcast_3_piece2 stored as bytes in memory (estimated size 2.8 MB, free 205.4 MB)
2019-06-15 05:02:08 INFO  BlockManagerInfo:54 - Added broadcast_3_piece2 in memory on ip-10-0-0-9.ec2.internal:46643 (size: 2.8 MB, free: 354.0 MB)
2019-06-15 05:02:08 INFO  SparkContext:54 - Created broadcast 3 from broadcast at SparkPipe.java:413
2019-06-15 05:02:08 INFO  MemoryStore:54 - Block broadcast_4 stored as values in memory (estimated size 5.9 KB, free 205.4 MB)
2019-06-15 05:02:08 INFO  MemoryStore:54 - Block broadcast_4_piece0 stored as bytes in memory (estimated size 381.0 B, free 205.4 MB)
2019-06-15 05:02:08 INFO  BlockManagerInfo:54 - Added broadcast_4_piece0 in memory on ip-10-0-0-9.ec2.internal:46643 (size: 381.0 B, free: 354.0 MB)
2019-06-15 05:02:08 INFO  SparkContext:54 - Created broadcast 4 from broadcast at SparkPipe.java:414
2019-06-15 05:02:08 INFO  MemoryStore:54 - Block broadcast_5 stored as values in memory (estimated size 16.4 KB, free 205.4 MB)
2019-06-15 05:02:08 INFO  MemoryStore:54 - Block broadcast_5_piece0 stored as bytes in memory (estimated size 8.1 KB, free 205.4 MB)
2019-06-15 05:02:08 INFO  BlockManagerInfo:54 - Added broadcast_5_piece0 in memory on ip-10-0-0-9.ec2.internal:46643 (size: 8.1 KB, free: 354.0 MB)
2019-06-15 05:02:08 INFO  SparkContext:54 - Created broadcast 5 from broadcast at SparkPipe.java:415
SparkHit 05:02:08 Spark kryo reference data structure serialization time : 964 ms
2019-06-15 05:02:09 INFO  deprecation:1173 - mapred.output.dir is deprecated. Instead, use mapreduce.output.fileoutputformat.outputdir
2019-06-15 05:02:09 INFO  FileOutputCommitter:108 - File Output Committer Algorithm version is 1
2019-06-15 05:02:09 INFO  FileInputFormat:249 - Total input paths to process : 1
2019-06-15 05:02:09 INFO  SparkContext:54 - Starting job: runJob at SparkHadoopWriter.scala:78
2019-06-15 05:02:09 INFO  DAGScheduler:54 - Got job 0 (runJob at SparkHadoopWriter.scala:78) with 1 output partitions
2019-06-15 05:02:09 INFO  DAGScheduler:54 - Final stage: ResultStage 0 (runJob at SparkHadoopWriter.scala:78)
2019-06-15 05:02:09 INFO  DAGScheduler:54 - Parents of final stage: List()
2019-06-15 05:02:09 INFO  DAGScheduler:54 - Missing parents: List()
2019-06-15 05:02:09 INFO  DAGScheduler:54 - Submitting ResultStage 0 (MapPartitionsRDD[5] at saveAsTextFile at SparkPipe.java:512), which has no missing parents
2019-06-15 05:02:09 INFO  MemoryStore:54 - Block broadcast_6 stored as values in memory (estimated size 21.5 MB, free 183.9 MB)
2019-06-15 05:02:09 INFO  MemoryStore:54 - Block broadcast_6_piece0 stored as bytes in memory (estimated size 149.8 KB, free 183.7 MB)
2019-06-15 05:02:09 INFO  BlockManagerInfo:54 - Added broadcast_6_piece0 in memory on ip-10-0-0-9.ec2.internal:46643 (size: 149.8 KB, free: 353.9 MB)
2019-06-15 05:02:09 INFO  SparkContext:54 - Created broadcast 6 from broadcast at DAGScheduler.scala:1039
2019-06-15 05:02:09 INFO  DAGScheduler:54 - Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[5] at saveAsTextFile at SparkPipe.java:512) (first 15 tasks are for partitions Vector(0))
2019-06-15 05:02:09 INFO  TaskSchedulerImpl:54 - Adding task set 0.0 with 1 tasks
2019-06-15 05:02:09 INFO  TaskSetManager:54 - Starting task 0.0 in stage 0.0 (TID 0, 10.0.0.12, executor 2, partition 0, PROCESS_LOCAL, 7914 bytes)
2019-06-15 05:02:10 INFO  BlockManagerInfo:54 - Added broadcast_6_piece0 in memory on 10.0.0.12:45298 (size: 149.8 KB, free: 366.2 MB)
2019-06-15 05:02:10 INFO  BlockManagerInfo:54 - Added broadcast_0_piece0 in memory on 10.0.0.12:45298 (size: 23.2 KB, free: 366.1 MB)
2019-06-15 05:02:11 INFO  BlockManagerInfo:54 - Added broadcast_1_piece0 in memory on 10.0.0.12:45298 (size: 1472.5 KB, free: 364.7 MB)
2019-06-15 05:02:11 INFO  BlockManagerInfo:54 - Added broadcast_3_piece2 in memory on 10.0.0.12:45298 (size: 2.8 MB, free: 361.9 MB)
2019-06-15 05:02:11 INFO  BlockManagerInfo:54 - Added broadcast_3_piece0 in memory on 10.0.0.12:45298 (size: 4.0 MB, free: 357.9 MB)
2019-06-15 05:02:11 INFO  BlockManagerInfo:54 - Added broadcast_3_piece1 in memory on 10.0.0.12:45298 (size: 4.0 MB, free: 353.9 MB)
2019-06-15 05:02:13 INFO  BlockManagerInfo:54 - Added broadcast_2_piece0 in memory on 10.0.0.12:45298 (size: 80.0 B, free: 353.9 MB)
2019-06-15 05:02:13 INFO  BlockManagerInfo:54 - Added broadcast_5_piece0 in memory on 10.0.0.12:45298 (size: 8.1 KB, free: 353.9 MB)
2019-06-15 05:02:20 INFO  TaskSetManager:54 - Finished task 0.0 in stage 0.0 (TID 0) in 10815 ms on 10.0.0.12 (executor 2) (1/1)
2019-06-15 05:02:20 INFO  TaskSchedulerImpl:54 - Removed TaskSet 0.0, whose tasks have all completed, from pool 
2019-06-15 05:02:20 INFO  DAGScheduler:54 - ResultStage 0 (runJob at SparkHadoopWriter.scala:78) finished in 11.160 s
2019-06-15 05:02:20 INFO  DAGScheduler:54 - Job 0 finished: runJob at SparkHadoopWriter.scala:78, took 11.243498 s
2019-06-15 05:02:20 INFO  SparkHadoopWriter:54 - Job job_20190615050209_0005 committed.
2019-06-15 05:02:20 INFO  AbstractConnector:318 - Stopped Spark@22bdd442{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2019-06-15 05:02:20 INFO  SparkUI:54 - Stopped Spark web UI at http://ec2-107-21-13-191.compute-1.amazonaws.com:4040
2019-06-15 05:02:20 INFO  StandaloneSchedulerBackend:54 - Shutting down all executors
2019-06-15 05:02:20 INFO  CoarseGrainedSchedulerBackend$DriverEndpoint:54 - Asking each executor to shut down
2019-06-15 05:02:20 INFO  MapOutputTrackerMasterEndpoint:54 - MapOutputTrackerMasterEndpoint stopped!
2019-06-15 05:02:20 INFO  MemoryStore:54 - MemoryStore cleared
2019-06-15 05:02:20 INFO  BlockManager:54 - BlockManager stopped
2019-06-15 05:02:20 INFO  BlockManagerMaster:54 - BlockManagerMaster stopped
2019-06-15 05:02:20 INFO  OutputCommitCoordinator$OutputCommitCoordinatorEndpoint:54 - OutputCommitCoordinator stopped!
2019-06-15 05:02:20 INFO  SparkContext:54 - Successfully stopped SparkContext
2019-06-15 05:02:20 INFO  ShutdownHookManager:54 - Shutdown hook called
2019-06-15 05:02:20 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-d90d51ea-58e5-485b-b494-0b27f7d5d1a8
2019-06-15 05:02:20 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-4eaa90f8-adf6-41cb-a726-03fcfd969904
ubuntu@ip-10-0-0-9:~$ ls -al ./sparkhit-latest/example/stool-result1
total 12
drwxrwxr-x 2 ubuntu ubuntu 4096 Jun 15 05:02 .
drwxrwxr-x 5 ubuntu ubuntu 4096 Jun 15 05:02 ..
-rw-r--r-- 1 ubuntu ubuntu    0 Jun 15 05:02 _SUCCESS
-rw-r--r-- 1 ubuntu ubuntu    8 Jun 15 05:02 ._SUCCESS.crc`

**Comment by rhinempi** [comment]
Hi Jing,

is your output path ./sparkhit-latest/example/stool-result1 shared across all worker nodes?
if not, can you check the same path on other worker nodes.

You can add one more option    <code>-partition 6</code>  to repartition the input data. Run it again and see if there is partial result on the output directory.

Li

**Comment by jing0703** [comment]
Hi Li,
The output file path is shared with master and all workers. The output file is not written when I apply task by master node, however, I could get output when apply the same task with one of the workers. It seems that the workers don't have access to write to master or there are other issues with my spark cluster configuration.  I finally changed the output path to a S3 bucket and it working now. 

I  am trying to set up a metagenomics analysis pipeline with sparkhit mapper and reporter function.
I am wondering if there is any way that I could mapping the same sequence with different ref genome quickly? Thank you very much for all your help!

Jing

**Comment by rhinempi** [comment]
Hi Jing,

good to hear that it works.

For multiple reference genomes, you can simply combine the sequences into one file. The reporter should report the mapping result separately.

Li

**Comment by jing0703** [comment]
Hi Li, thank you very much for you suggestions! I tried to combine several reference genomes and save it as one fastq file in s3 bucket, but it seems that sparkhit mapper only read ref genome from local, I am wondering if there is anyway to let the mapper load ref from s3?

Another question is that the output file path for reporter can not be recognized:
`ubuntu@ip-10-0-0-9:~$ ./sparkhit-latest/bin/sparkhit reporter -input "./otu/part*" -word 9 -outfile ./stool.report.txt
/usr/local/spark/bin/spark-submit --class uni.bielefeld.cmg.sparkhit.main.MainOfReporter ./sparkhit-latest/lib/original-sparkhit-1.0.jar -input ./otu/part-00000 ./otu/part-00001 ./otu/part-00002 ./otu/part-00003 ./otu/part-00004 ./otu/part-00005 ./otu/part-00006 ./otu/part-00007 ./otu/part-00008 ./otu/part-00009 ./otu/part-00010 -word 9 -outfile ./stool.report.txt
2019-06-18 03:58:32 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
SparkHit 03:58:32 SparkHit Reporter initiating ... 
SparkHit 03:58:32 interpreting parameters.
SparkHit 03:58:32 Output file not set of -outfile options
SparkHit 03:58:32 Parameter settings incorrect.
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at uni.bielefeld.cmg.sparkhit.util.ParameterForReporter.importCommandLine(ParameterForReporter.java:216)
	at uni.bielefeld.cmg.sparkhit.main.MainOfReporter.main(MainOfReporter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2019-06-18 03:58:32 INFO  ShutdownHookManager:54 - Shutdown hook called
2019-06-18 03:58:32 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-433dcd10-7f6b-444a-8eb4-38359727d54b`
Could you also kindly provide some information for the field of mapping result? I can not find it in documentation. 
`@HWUSI-EAS1593_103090650:7:100:17269:9741/1	69nt	3.30e-27	69	1	69	-	95.65	NC_000913.3	4167571	4167639
@HWUSI-EAS1593_103090650:7:100:17269:9741/1	69nt	3.30e-27	69	1	69	-	95.65	NC_000913.3	4209059	4209127
@HWUSI-EAS1593_103090650:7:100:2846:19386/1	91nt	3.49e-39	87	5	91	-	93.41	NC_000913.3	4272964	4273050
`
Thanks again for all your help!
Jing
